# Generated by Django 5.2 on 2025-05-22 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(default='yds', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('company_name', models.CharField(default='NONE', max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=50)),
                ('email', models.CharField(default='NONE', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('nid_no', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Challan',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('total', models.CharField(max_length=100)),
                ('current_status', models.CharField(default='NOT-PAID', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CashMemo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('total_yds', models.BigIntegerField()),
                ('total_amount', models.BigIntegerField()),
                ('discount', models.FloatField(default=0, max_length=100)),
                ('total_after_discount', models.FloatField(default=0, max_length=100)),
                ('discount_method', models.CharField(default='%', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customer')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeBill',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('total_amount', models.FloatField()),
                ('current_status', models.CharField(default='NOT-PAID', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('rate', models.IntegerField()),
                ('production_cost', models.FloatField(db_column='production_cost')),
                ('other_cost', models.FloatField(db_column='other_cost', default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(db_column='catagory_id', on_delete=django.db.models.deletion.RESTRICT, to='api.category')),
            ],
        ),
        migrations.CreateModel(
            name='CashMemoChallan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cashmemo', models.ForeignKey(db_column='cash_memo_id', on_delete=django.db.models.deletion.CASCADE, to='api.cashmemo')),
                ('challan', models.ForeignKey(db_column='challan_id', on_delete=django.db.models.deletion.CASCADE, to='api.challan')),
                ('product', models.ForeignKey(db_column='products_id', on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.FloatField()),
                ('rate', models.FloatField()),
                ('payment', models.CharField(default='NOT-PAID', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
                ('product', models.ForeignKey(db_column='products_id', on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('current_status', models.CharField(default='IN-STOCK', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
                ('product', models.ForeignKey(db_column='products_id', on_delete=django.db.models.deletion.CASCADE, to='api.product')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.production')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeBillProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField()),
                ('quantity', models.FloatField()),
                ('amount', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_bill_id', models.ForeignKey(db_column='employee_bill_id', on_delete=django.db.models.deletion.CASCADE, to='api.employeebill')),
                ('product', models.ForeignKey(db_column='products_id', on_delete=django.db.models.deletion.CASCADE, to='api.product')),
                ('production', models.ForeignKey(db_column='production_id', on_delete=django.db.models.deletion.CASCADE, to='api.production')),
            ],
        ),
        migrations.CreateModel(
            name='ChallanProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('challan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.challan')),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
                ('product', models.ForeignKey(db_column='products_id', on_delete=django.db.models.deletion.CASCADE, to='api.product')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.production')),
            ],
        ),
    ]
