services:
  web:
    container_name: business_management_nft_frontend
    build: ./frontend
    env_file:
      - ./frontend/.env.local
    ports:
      - "3000:3000"
    depends_on:
      - api

  api:
    container_name: business_management_nft_backend
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - POSTGRES_HOST=db
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: business_management_nft_db
    env_file: "./backend/.env"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    name: business_management_nft_postgres_volume
