services:
  web:
    container_name: team_track_frontend
    build: ./team_track
    env_file:
      - ./frontend/.env.local
    ports:
      - "3000:3000"
    depends_on:
      - api

  api:
    container_name: team_track_backend
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      MYSQL_HOST: db

  db:
    image: postgres:latest
    container_name: business_management_nft_db
    env_file: "./backend/.env"
