services:
  web:
    container_name: team_track_frontend
    build: ./team_track
    env_file:
      - ./team_track/.env.local
    ports:
      - "3000:3000"
    depends_on:
      - api

  api:
    container_name: team_track_backend
    build: ./InvoiceManager_v5
    ports:
      - "8000:8000"
    env_file:
      - ./InvoiceManager_v5/.env
    environment:
      MYSQL_HOST: db

    depends_on:
      - db

  db:
    container_name: team_track_db
    image: mysql:8.0
    ports:
      - "3306:3306"
    env_file:
      - ./InvoiceManager_v5/.env
    volumes:
      - team_track_db:/var/lib/mysql

volumes:
  team_track_db:
    name: team_track_mysql_volume
